fidos = {
  editPage: {
    myKey: 'editPage',
		title: 'Edit Page Info',
		instructions: 'Edit the page details here',
		class: 'twoColumn',
		init: function() {
			$AM('#PageName').attr('value', $AM.SAM.page.name);
			$AM('#PageTitle').attr('value', $AM.SAM.page.title);
			$AM('#FileName').attr('value', $AM.SAM.page.file);
			$AM('#PageManualPath').attr('value', $AM.SAM.page.href);
			$AM._.each ( $AM.SAM.presentation.template, function (obj, key) {
				if (obj.id === $AM.SAM.page["apply-template-id"]) {
					$AM('#PageTemplateFK').append('<option value="'+obj.id+'" selected="true">'+key+'</option>');
				} else {
					$AM('#PageTemplateFK').append('<option value="'+obj.id+'">'+key+'</option>');
				};
			});	
			$AM('#SSLRequired').attr('checked', $AM.SAM.page["ssl-required"]);
			$AM('#noindex').attr('checked', $AM.SAM.page["noindex"]);
			$AM('#nofollow').attr('checked', $AM.SAM.page["nofollow"]);
			$AM('#openNewWindow').attr('checked', $AM.SAM.page["openNewWindow"]);
			$AM('#PageNavigable').attr('checked', $AM.SAM.page["navigable"]);
			$AM('#PagePrintable').attr('checked', $AM.SAM.page["printable"]);
			$AM('#RSSFeed').attr('checked', $AM.SAM.page["rssfeed"]);
			$AM('#pageid').attr('value', $AM.SAM.page.id);
		},
		fields: {
			PageName: { 
				rules: { SAMmaxlength: 255, SAMreclength: 60, SAMrequired: true }, 
				type: 'text', 
				label: 'Navigation Label', 
				tooltip: 'This value is used in the SAM generated navigation and is the default value used in the URL',
				class: 'left',
				value: '' 
			},
			PageTitle: { 
				rules: { SAMmaxlength: 255, SAMreclength: 60 }, 
				type: 'text', 
				label: 'Page Title', 
				tooltip: 'This value is used in the title tag and will appear in the browser chrome and search results',
				class: 'left',
				value: '' 
			},
			FileName: { 
				rules: { SAMmaxlength: 255, SAMreclength: 60 }, 
				type: 'text', 
				label: 'File Name', 
				tooltip: 'This value will replace the page name generated by the Navigation Label. It is useful for sites whose language uses a non-roman alphabet.',
				class: 'left',
				value: '',
			},
			PageManualPath: { 
				rules: { SAMmaxlength: 511 }, 
				type: 'text', 
				label: 'Manual URL Override', 
				tooltip: 'This value will override the value used in internal links to this page',
				class: 'left',
				value: '',
			},
			PageTemplateFK: {
				type: 'select',
				label: 'Page Template',
				class: 'left',
				options: [],
			},
			openNewWindow: {
				type: 'checkbox',
				label: 'Open In New Window',
				tooltip: 'When checked, all internal links to this page will include target="_blank"',
				class: 'right',
				value: 0,
				style: 'padding-top:18px;'
			},
			PageNavigable: {
				type: 'checkbox',
				label: 'Visible in Navigation',
				tooltip: 'When checked, links to this page will appear in the SAM generated navigation',
				class: 'right',
				value: 1,
				style: 'padding-top:2px;'
			},
			PagePrintable: {
				type: 'checkbox',
				label: 'Page Printable',
				tooltip: 'When checked, the printable tag for this page will be set to true',
				class: 'right',
				value: 1,
				style: 'padding-top:2px;'
			},
			SSLRequired: {
				type: 'checkbox',
				label: 'SSL (HTTPS) Required',
				tooltip: 'When checked, all internal links to this page will use the https protocol',
				class: 'right',
				value: 0,
				style: 'padding-top:2px;'
			},
			RSSFeed: {
				type: 'checkbox',
				label: 'RSS Root',
				tooltip: 'When checked, an RSS feed will be generated for descendants of this page',
				class: 'right',
				value: 0,
				style: 'padding-top:2px;'
			},
			nofollow: {
				type: 'checkbox',
				label: 'No Follow Links',
				tooltip: 'When checked, links to this page will include the nofollow parameter',
				class: 'right',
				value: 0,
				style: 'padding-top:2px;'
			},
			noindex: {
				type: 'checkbox',
				label: 'Do Not Index',
				tooltip: 'When checked, this page will include a meta robots nofollow tag, and this page will be set to nofollow in robots.txt',
				class: 'right',
				value: 0,
				style: 'padding-top:2px;'
			},
			action: { type: 'hidden', value: 'editpage', column: 'bottom'  },
			pageid: { type: 'hidden', value: 0, column: 'bottom' }
		}
	}
} 
